# Generated by Django 3.2.7 on 2021-09-17 19:35

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('open_api_spec_file', models.FileField(blank=True, max_length=200, null=True, upload_to=core.models.open_api_spec_upload_path, verbose_name='Open API Specification file')),
                ('operation_dep_graph_file', models.FileField(blank=True, max_length=200, null=True, upload_to=core.models.open_api_spec_upload_path, verbose_name='Operation Dependency Graph file')),
                ('number_of_test_cases', models.IntegerField(default=1, verbose_name='Number of to be generated test cases')),
                ('use_example', models.BooleanField(default=True, verbose_name='Use examples provided by specification')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'TestPlan',
                'verbose_name_plural': 'TestPlans',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Result')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.testplan', verbose_name='Test Suite')),
            ],
            options={
                'verbose_name': 'TestSuite',
                'verbose_name_plural': 'TestSuites',
            },
        ),
    ]
