# Generated by Django 3.2.7 on 2021-09-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210917_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.testplan', verbose_name='Test Plan'),
        ),
    ]
