# Generated by Django 3.2.7 on 2021-09-20 20:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_testsuite_test_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='operation_dep_graph_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=core.models.operation_dep_graph_upload_path, verbose_name='Operation Dependency Graph file'),
        ),
    ]
