# Generated by Django 3.2.7 on 2021-09-20 20:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_testsuite_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='result',
        ),
        migrations.AddField(
            model_name='testsuite',
            name='result_error',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=core.models.generated_test_cases_upload_path, verbose_name='Error Test Cases Result'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='result_nominal',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=core.models.generated_test_cases_upload_path, verbose_name='Nominal Test Cases Result'),
        ),
    ]
